name: Test based on GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
   workflow_dispatch:
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was manually triggered."